"""add pending registration table

Revision ID: 118281aeeefd
Revises: 04e3bbe8af16
Create Date: 2026-06-25 00:30:07.370498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118281aeeefd'
down_revision: Union[str, Sequence[str], None] = '04e3bbe8af16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('otp', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_registration_email'), 'pending_registration', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_registration_email'), table_name='pending_registration')
    op.drop_table('pending_registration')
    # ### end Alembic commands ###
