"""create activities participants refresh_token tables and update users

Revision ID: 1802ae5d82c3
Revises: f367d1dcedf2
Create Date: 2026-06-23 00:21:13.912993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1802ae5d82c3'
down_revision: Union[str, Sequence[str], None] = 'f367d1dcedf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
