"""add location and gender to users

Revision ID: 3a7b7716766a
Revises: 140d632314aa
Create Date: 2026-06-24 00:34:57.401260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7b7716766a'
down_revision: Union[str, Sequence[str], None] = '140d632314aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=15), nullable=False))
    op.add_column('users', sa.Column('location', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
