"""added public_id uuid to users

Revision ID: 3e273fabb7e3
Revises: 8927d9131544
Create Date: 2026-06-30 19:44:43.281892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e273fabb7e3'
down_revision: Union[str, Sequence[str], None] = '8927d9131544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('users', sa.Column('public_id', sa.UUID(), nullable=True))
    op.execute('UPDATE users SET public_id = gen_random_uuid() WHERE public_id IS NULL')
    op.alter_column('users', 'public_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
