"""add unique constraint to participants

Revision ID: 66698451aa04
Revises: b5fc3a63b4c2
Create Date: 2026-06-28 18:58:40.544751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66698451aa04'
down_revision: Union[str, Sequence[str], None] = 'b5fc3a63b4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_activity', 'participants', ['user_id', 'activity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_activity', 'participants', type_='unique')
    # ### end Alembic commands ###
