"""add public_id to activities and participants

Revision ID: e74115eca64a
Revises: 3e273fabb7e3
Create Date: 2026-07-01 12:07:47.860075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'e74115eca64a'
down_revision: Union[str, Sequence[str], None] = '3e273fabb7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: add column as nullable
    op.add_column('activities', sa.Column('public_id', sa.UUID(), nullable=True))
    op.add_column('participants', sa.Column('public_id', sa.UUID(), nullable=True))
    
    # Step 2: backfill existing rows with random UUIDs
    connection = op.get_bind()
    
    activities = connection.execute(text("SELECT id FROM activities")).fetchall()
    for row in activities:
        connection.execute(
            text("UPDATE activities SET public_id = :pid WHERE id = :id"),
            {"pid": str(uuid.uuid4()), "id": row[0]}
        )
    
    participants = connection.execute(text("SELECT id FROM participants")).fetchall()
    for row in participants:
        connection.execute(
            text("UPDATE participants SET public_id = :pid WHERE id = :id"),
            {"pid": str(uuid.uuid4()), "id": row[0]}
        )
    
    # Step 3: now enforce not-null and unique
    op.alter_column('activities', 'public_id', nullable=False)
    op.alter_column('participants', 'public_id', nullable=False)
    
    op.create_index('ix_activities_public_id', 'activities', ['public_id'], unique=True)
    op.create_index('ix_participants_public_id', 'participants', ['public_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_participants_public_id'), table_name='participants')
    op.drop_column('participants', 'public_id')
    op.drop_index(op.f('ix_activities_public_id'), table_name='activities')
    op.drop_column('activities', 'public_id')
    # ### end Alembic commands ###
